#!/bin/bash
total 20
-rwxr--r-- 1 root root 16 May 27 09:39 0-current_working_directory
-rwxr--r-- 1 root root 15 May 27 12:09 1-listit
-rw-r--r-- 1 root root 43 May 27 12:52 2-bring_me_home
-rw-r--r-- 1 root root 12 May 27 13:01 3-listfiles
-rw-r--r-- 1 root root 80 May 27 09:47 README.md
